spring.application.name=msgconsumer

# IBM MQ Configuration
ibm.mq.queue-manager=QM1
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.conn-name=localhost(1414)
ibm.mq.queue=DEV.QUEUE.1
ibm.mq.user=app
ibm.mq.password=passw0rd